koi:
    resource: "@KoiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@KoiBundle/Controller/"
    type:     annotation

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

