<?php

namespace KoiBundle\Repository;

/**
 * FeedElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedElementRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll() {
		$query = $this->createQueryBuilder('e')
			->select('e.idFeed', 'e.idElement', 'e.amount')
			->getQuery();

		return $feed_elements = $query->getResult();
	}

	public function getByFeed($feed) {
		$query = $this->createQueryBuilder('f')
			->where('f.idFeed = :param')
			->setParameter('param', $feed)
			->getQuery();

		return $feed_elements = $query->getResult();
	}

	// Admin function --------------------------------------------------------------------------------------------------

	public function getDelete($id)
	{
		$query = "";
		$key = "";

		foreach ($id as $key => $value) {
			if ($key != "") {
				$query = $this->createQueryBuilder('f')
					->delete()
					->where('f.idFeed = ' . $key)
					->getQuery()->execute();
			}
		}
		return array($query, $key);
	}

}
