<?php

namespace KoiBundle\Repository;

/**
 * FeedComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedComponentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByFeed($feed) {
		$query = $this->createQueryBuilder('f')
			->where('f.idFeed = :param')
			->setParameter('param', $feed)
			->getQuery();

		return $query->getResult();
	}
}
